[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_nft_anchor_project = "7MAAvN5SsG52Veqg2dNXa7cuUKEXKj96bwzNSjTswKTw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/solana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
