[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft_anchor_project = "2STkCaRwFSPpCjmoV212Rn4xR5QBbMeWRyCvPVBKWq9Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/solana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
